language: cpp
compiler:
  - clang
  - gcc
dist: trusty

before_script:
  - uname -a
  - ./tools/ci/sql.sh
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-5 -y
  - sudo apt-get install g++-5 -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 1
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 1

script:
  - ./configure $CONFIGURE_FLAGS
  - ./tools/ci/npc.sh
  - make clean
  - make server
  - ./login-server --run-once
  - ./char-server --run-once
  - ./map-server --run-once

env:
  global:
    - DB_ROOT="root"
    - DB_HOST="127.0.0.1"
    - DB_NAME="ragnarok"
    - DB_USER="ragnarok"
    - DB_PASS="ragnarok"
  matrix:
    - CONFIGURE_FLAGS="--enable-prere=no --enable-vip=no --enable-buildbot=yes"
    - CONFIGURE_FLAGS="--enable-prere=yes --enable-vip=no --enable-buildbot=yes"
    - CONFIGURE_FLAGS="--enable-prere=no --enable-vip=yes --enable-buildbot=yes"
    - CONFIGURE_FLAGS="--enable-prere=yes --enable-vip=yes --enable-buildbot=yes"

notifications:
  email: false
